# Generated by Django 4.1.1 on 2022-09-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('date_of_application', models.DateField()),
                ('stage', models.CharField(choices=[('application submitted', 'application submitted'), ('phone screen', 'phone screen'), ('on-site interview', 'on-site interview')], max_length=50)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending')], max_length=50)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
    ]
