# Generated by Django 4.1.1 on 2022-09-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
